services:
  - type: web
    name: pddarzan
    runtime: node
    plan: free
    buildCommand: npm install && npm rebuild sqlite3 --build-from-source
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_jTApBoRcZ32z@ep-floral-art-aym4jtfi-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20


